[package]
name = "VE"
version = "0.0.0"
edition = "2024"

[dependencies]
gl = "0.14.0"
gl_loader = "0.1.2"
glfw = "0.60.0"
glm = "0.3.0"
glu-sys = "0.1.4"
image = "0.25.8"

[profile.dev]
incremental = true

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
